version: 2
updates:
  - package-ecosystem: "npm" # If you are using npm
    directory: "/client"     # Path to your frontend package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/server"     # Path to your backend package.json
    schedule:
      interval: "weekly"